var nome = "Beatriz";
var banco = "Bradesco";
var agencia = 7354;
var conta = 257755;
var saldo = 15000;
console.log("Olá, seja bem vinda", nome, "a sua conta do", banco);
console.log("Seu número de agência é:", agencia);
console.log("Os dados da sua conta são:", conta);
console.log("saldo disponivel em conta: R$", saldo);
saldo += 500;
console.log("você recebeu um pix de: R$", 500);
saldo += 700;
console.log("Você recebeu uma transferencia de: R$", 700);
saldo += 200;
console.log("Você depositou: R$", 200);
saldo -= 150;
console.log("Compra da SHEIN efetuada: R$", 150);
saldo -= 500;
console.log("Você realizou um pix de: R$", 500);
console.log("Seu saldo total é de: R$", saldo);
